# -*- coding: utf-8 -*-
"""terrain_errosion

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CkfS481YyYDksnc2jUl9UzFPFmuZSuyY
"""

from google.colab import drive
drive.mount('/content/drive')

import cv2
import numpy as np
import pandas as pd
import os
import matplotlib.pyplot as plt
import seaborn as sns

IMAGE_DIR = "/content/drive/MyDrive/yolo_projects/archaeological-yolo.v2i.yolov8/train/images"

features = []

for img_name in os.listdir(IMAGE_DIR):
    img_path = os.path.join(IMAGE_DIR, img_name)

    img = cv2.imread(img_path)
    if img is None:
        continue

    img = cv2.resize(img, (512, 512))

    # Vegetation score (green intensity)
    vegetation_ratio = np.mean(img[:, :, 1]) / 255.0

    # Slope score (edge intensity)
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    grad_x = cv2.Sobel(gray, cv2.CV_64F, 1, 0, ksize=3)
    grad_y = cv2.Sobel(gray, cv2.CV_64F, 0, 1, ksize=3)
    slope_score = np.mean(np.sqrt(grad_x**2 + grad_y**2)) / 255.0

    # Rule-based label
    erosion_label = 1 if (vegetation_ratio < 0.4 and slope_score > 0.4) else 0

    features.append([vegetation_ratio, slope_score, erosion_label])

df = pd.DataFrame(
    features,
    columns=["vegetation_ratio", "slope_score", "erosion_label"]
)

df.to_csv("/content/drive/MyDrive/erosion_features.csv", index=False)
print("✅ Feature dataset saved")
df.head()

from sklearn.model_selection import train_test_split

X = df[["vegetation_ratio", "slope_score"]]
y = df["erosion_label"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.25,
    random_state=42,
    stratify=y
)

from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(
    n_estimators=200,
    random_state=42
)

model.fit(X_train, y_train)
print("✅ Erosion model trained")

from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

y_pred = model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy:.4f}")

print("\nClassification Report:")
print(classification_report(
    y_test,
    y_pred,
    target_names=["Stable", "Erosion-Prone"]
))

cm = confusion_matrix(y_test, y_pred)

plt.figure(figsize=(5,4))
sns.heatmap(
    cm,
    annot=True,
    fmt="d",
    cmap="Blues",
    xticklabels=["Stable", "Erosion-Prone"],
    yticklabels=["Stable", "Erosion-Prone"]
)
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Terrain Erosion Prediction")
plt.show()

import joblib

MODEL_PATH = "/content/drive/MyDrive/erosion_model.pkl"
joblib.dump(model, MODEL_PATH)

print("✅ Erosion model saved to Google Drive")