# -*- coding: utf-8 -*-
"""yolo

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZEBMzlzMAHioe330Y1d8j-QerMvcqpHj
"""

from google.colab import drive
drive.mount('/content/drive')

DATASET_PATH = "/content/drive/MyDrive/yolo_projects/archaeological-yolo.v2i.yolov8"

import os
print("Dataset exists:", os.path.exists(DATASET_PATH))
print("\nTop-level contents:")
!ls $DATASET_PATH

!ls $DATASET_PATH/train/images
!ls $DATASET_PATH/train/labels

import os

# Define the local path for data.yaml for reliable access
LOCAL_DATA_YAML_PATH = "/content/data.yaml"

# Write the data.yaml file to the local filesystem
# The 'path' inside data.yaml should still point to the main dataset directory on Google Drive
# The 'train' and 'val' sub-paths are relative to this 'path'
with open(LOCAL_DATA_YAML_PATH, 'w') as f:
    f.write(f"path: {DATASET_PATH}\n") # DATASET_PATH is the original path on Google Drive
    f.write("train: train/images\n")
    f.write("val: valid/images\n")
    f.write("nc: 3\n")
    f.write("names:\n")
    f.write("  - artifact\n")
    f.write("  - ruins\n")
    f.write("  - structure\n")

print(f"data.yaml successfully written to {LOCAL_DATA_YAML_PATH}")

!pip install -U ultralytics

from ultralytics import YOLO
print("YOLO imported successfully")

model = YOLO("yolov8n.pt")
print("YOLOv8 nano model loaded")

!ls /content/drive/MyDrive/yolo_projects

!ls /content/drive/MyDrive/yolo_projects/archaeological-yolo.v2i.yolov8

# Commented out IPython magic to ensure Python compatibility.
# %%writefile /content/drive/MyDrive/yolo_projects/archaeological-yolo.v2i.yolov8/data.yaml
# path: /content/drive/MyDrive/yolo_projects/archaeological-yolo.v2i.yolov8
# 
# train: train/images
# val: train/valid/images
# 
# nc: 3
# names:
#   - artifact
#   - ruins
#   - structure

!ls $DATASET_PATH/train/valid/images

!ls /content/drive/MyDrive/yolo_projects/archaeological-yolo.v2i.yolov8

from ultralytics import YOLO

model = YOLO("yolov8n.pt")

model.train(
    data="/content/drive/MyDrive/yolo_projects/archaeological-yolo.v2i.yolov8/data.yaml",
    epochs=50,
    imgsz=640,
    batch=8,
    device=0
)

import glob

weight_files = glob.glob("/content/runs/detect/*/weights/best.pt")
print("Found weight files:")
for w in weight_files:
    print(w)

import os
import shutil

SAVE_DIR = "/content/drive/MyDrive/yolo_models"
os.makedirs(SAVE_DIR, exist_ok=True)

shutil.copy(
    "/content/runs/detect/train9/weights/best.pt",
    f"{SAVE_DIR}/archaeological_yolo_best.pt"
)

print("✅ Best YOLO model saved permanently to Google Drive")

!ls /content/drive/MyDrive/yolo_models

from ultralytics import YOLO

model = YOLO("/content/drive/MyDrive/yolo_models/archaeological_yolo_best.pt")
print("✅ Trained YOLO model loaded successfully")

metrics = model.val(
    data="/content/drive/MyDrive/yolo_projects/archaeological-yolo.v2i.yolov8/data.yaml",
    imgsz=640
)

print(metrics)

model.predict(
    source="/content/drive/MyDrive/yolo_projects/archaeological-yolo.v2i.yolov8/train/valid/images",
    conf=0.25,
    save=True
)

from PIL import Image
import matplotlib.pyplot as plt
import os

pred_dir = "/content/runs/detect/predict"
img_name = os.listdir(pred_dir)[0]

img = Image.open(os.path.join(pred_dir, img_name))
plt.imshow(img)
plt.axis("off")

import glob

pred_dirs = glob.glob("/content/runs/detect/predict*")
print("Prediction folders found:")
for d in pred_dirs:
    print(d)

from PIL import Image
import matplotlib.pyplot as plt
import os

pred_dir = "/content/runs/detect/predict3"  # latest folder
print("Using:", pred_dir)

img_name = os.listdir(pred_dir)[0]
print("Image:", img_name)

img = Image.open(os.path.join(pred_dir, img_name))
plt.imshow(img)
plt.axis("off")